%% Glare Illusion Paradigm - EyeLink Group Analysis

% This script requires outputs that are generated by running the script
% Glare_Illusion_EyeLink_Subject_Analysis_v5.m

% Written by: Sharif I. Kronemer
% Last Modified Date: 6/20/2025

% Version 2

clear all

%% Directories & Paths

% Root path
root_path = '/Users/kronemersi/Library/CloudStorage/OneDrive-NationalInstitutesofHealth/Cortical_Blindness_Study';

% Add permutation file path
addpath(genpath(fullfile(root_path,'Analysis_Code/EyeLink/Permutation_Analysis')))

% Subject data directory
data_dir = fullfile(root_path,'Analysis/Subject_Analysis');

% Output directory
output_dir = fullfile(root_path,'Analysis/Group_Analysis/EyeLink');

% Check output dir
if isempty(dir(output_dir))

    mkdir(output_dir)

end 

%% Subject/Group Selection

% Patient (1) or control group (0) or custom list (2)
group_type = 1; 

% Blink and saccade smoothing
blink_saccade_smoothing_span = 100;

% Define subjects to run
if group_type == 1

    % Patients list
    % Blind aware: P2 P4 P7 P8
    % Blind unaware: P1 P3 P5 P6
    subject_list = {'P1','P2','P3','P4','P5','P6','P7','P8'};

    % Group name
    group_name = 'Patients';

elseif group_type == 0

    % Controls list
    subject_list = {'C1','C2','C3','C4','C5','C6','C7','C8'};

    % Group name
    group_name = 'Controls';

else 

    % Custom list
    subject_list = {'P4'};

    group_name = 'Custom';

end

%% Parameters

% Define data types
data_list = {'pupil','blink','microsaccade'};

% Define event types
event_list = {'distractor','glare','nonglare','iso','white','ISI_glare_nonglare_white_iso',...
    'ISI_glare_nonglare_white','ISI_distractor','nontarget','ISI_glare','ISI_nonglare','ISI_white','ISI_iso'};

% Define sides
side_list = {'left_right','left','right'};

% Create plots (y = yes; n = no)
create_plots = 'n';

% Turn off warnings
warning('off','all')

%% Statistical Parameters

% Number of permutations
num_permutations = 1000;

% Are samples dependent (default is true)
dependent_samples = 'true';

% Define alpha threshold
p_threshold = 0.05;

% Two-sided
two_sided = 'true';

% Permuation baseline
perm_baseline = 8751:9000;

% Query interval
query_int = 8001:13000;

%% Combine Epochs Across Subjects

% Loop over data types
for data = 1:length(data_list)

    % Define data type
    data_type = data_list{data};

    disp(['Creating ',data_type,' group matrices...'])

    % Loop over event types
    for type = 1:length(event_list)

        % Define event type
        event_type = event_list{type};

        % Reset matrices - controls 
        if isequal(group_type,0)

            group_left_matrix = [];
            group_right_matrix = [];
            group_sighted_matrix = [];
            group_left_right_matrix = [];

            group_SEM_left_matrix = [];
            group_SEM_right_matrix = [];
            group_SEM_sighted_matrix = [];
            group_SEM_left_right_matrix = [];

        % Reset matrices - patients
        elseif isequal(group_type, 1)

            group_blinded_aware_matrix = [];
            group_blinded_unaware_matrix = [];
            group_sighted_matrix = [];

            group_SEM_blinded_aware_matrix = [];
            group_SEM_blinded_unaware_matrix = [];
            group_SEM_sighted_matrix = [];

        % Individual subjects
        else

            group_left_matrix = [];
            group_right_matrix = [];
            group_sighted_matrix = [];
            group_left_right_matrix = [];

            group_SEM_left_matrix = [];
            group_SEM_right_matrix = [];
            group_SEM_sighted_matrix = [];
            group_SEM_left_right_matrix = [];

            group_blinded_unaware_matrix = [];
            group_blinded_aware_matrix = [];
            group_sighted_matrix = [];

            group_SEM_blinded_unaware_matrix = [];
            group_SEM_blinded_aware_matrix = [];
            group_SEM_sighted_matrix = [];

        end

        % Loop over subjects
        for ID = 1:length(subject_list)

            % SubID
            subID = subject_list{ID};

            % Loop over side types
            for side = 1:length(side_list)

                % Define side type
                side_type = side_list{side}; 

                % Skip left_right side type for patients
                if isequal(group_type,1) && isequal(side_type,'left_right') 
                
                    continue

                end

                % Nontarget data
                % Note: Combination of the nontarget stimuli must be
                % performed manually - other data times can be loaded
                % independently for each subject without additional
                % analyses
                if isequal(event_type,'nontarget')

                    % Load data
                    load(fullfile(data_dir,subID,'OP4','Glare_illusion_EyeLink_results.mat'),['glare_',side_type,'_',data_type,'_epochs'],...
                        ['nonglare_',side_type,'_',data_type,'_epochs'],['white_',side_type,'_',data_type,'_epochs'],['iso_',side_type,'_',data_type,'_epochs']);

                    % Combine epochs across conditions
                    % glare/nonglare/white/iso
                    combined_epochs = eval(['[glare_',side_type,'_',data_type,'_epochs','; nonglare_',side_type,'_',data_type,'_epochs',...
                        '; white_',side_type,'_',data_type,'_epochs','; iso_',side_type,'_',data_type,'_epochs]']);

                    % Mean across epochs
                    test_data = mean(combined_epochs,1,"omitnan");

                    % Calculate SEM - exclude nan epochs
                    SEM_data = std(combined_epochs,[],1,'omitnan')/sqrt(size(combined_epochs,1));

                    % Smooth blink/microsaccade data
                    % Note: That subject level analyses will perform the
                    % same smoothing procedure on other mean trial types already
                    if ismember(data_type,['microsaccade','blink'])
                        
                        % Mean across epochs
                        test_data = movmean(test_data,blink_saccade_smoothing_span);

                        % Calculate SEM - exclude nan epochs
                        SEM_data = movmean((nanstd(combined_epochs,1)/sqrt(size(combined_epochs,1))),blink_saccade_smoothing_span);

                    end

                    % Clean workspace
                    clearvars(['glare_',side_type,'_',data_type,'_epochs'],['nonglare_',side_type,'_',data_type,'_epochs'],['white_',side_type,'_',data_type,'_epochs'],['iso_',side_type,'_',data_type,'_epochs'])

                % Load all other mean data
                else

                    % Load data
                    load(fullfile(data_dir,subID,'OP4','Glare_illusion_EyeLink_results.mat'),[event_type,'_',side_type,'_',data_type,'_epochs']);

                    % Remove last trial from P7
                    %if isequal(subID,'P7') && isequal(side_type,'left') && isequal(event_type,'nonglare') && isequal(data_type,'pupil')

                    %    eval([event_type,'_',side_type,'_',data_type,'_epochs(72,:) = [];'])

                    %end

                    % Mean across epochs
                    test_data = mean(eval([event_type,'_',side_type,'_',data_type,'_epochs']),1,"omitnan");

                    % Calculate SEM - exclude nan epochs
                    SEM_data = std(eval([event_type,'_',side_type,'_',data_type,'_epochs']),[],1,'omitnan')/sqrt(size(eval([event_type,'_',side_type,'_',data_type,'_epochs']),1));

                    % Clean workspace
                    clearvars(['mean_',event_type,'_',side_type,'_',data_type],['SEM_',event_type,'_',side_type,'_',data_type],[event_type,'_',side_type,'_',data_type,'_epochs'])

                end

                %% Categorize data according to the presentation location 

                % Left+right data
                if isequal(side_type,'left_right') 

                    % Add subject data
                    group_left_right_matrix = [group_left_right_matrix; test_data];

                % Left and right/sighted and blind only
                else
          
                    % Add subject data to group matrices

                    % Patients - Blind unaware
                    if ismember(subID,{'P3','P6'}) && isequal(side_type,'right') || ...
                            ismember(subID,{'P1','P5'}) && isequal(side_type,'left')
                     
                        % Add subject data
                        group_blinded_unaware_matrix = [group_blinded_unaware_matrix; test_data];
                        group_SEM_blinded_unaware_matrix = [group_SEM_blinded_unaware_matrix; SEM_data];

                    % Patients - Bind aware
                    elseif ismember(subID,{'P4'}) && isequal(side_type,'right') || ...
                            ismember(subID,{'P2','P7','P8'}) && isequal(side_type,'left')
                     
                        % Add subject data
                        group_blinded_aware_matrix = [group_blinded_aware_matrix; test_data];
                        group_SEM_blinded_aware_matrix = [group_SEM_blinded_aware_matrix; SEM_data];

                    % Patients - Sighted field
                    elseif ismember(subID,{'P3','P4','P6'}) && isequal(side_type,'left') || ...
                            ismember(subID,{'P1','P2','P5','P7','P8'}) && isequal(side_type,'right')
        
                        % Add subject data
                        group_sighted_matrix = [group_sighted_matrix; test_data];
                        group_SEM_sighted_matrix = [group_SEM_sighted_matrix; SEM_data];

                    % Controls - Sighted field
                    % Note: The sighted side is determined by the control
                    % participant's paired patient sighted side
                    elseif ismember(subID,{'C1','C5','C4',}) && isequal(side_type,'left') || ...
                            ismember(subID,{'C2','C3','C7','C6','C8'}) && isequal(side_type,'right')
        
                        % Add subject data
                        group_sighted_matrix = [group_sighted_matrix; test_data];
                        group_SEM_sighted_matrix = [group_SEM_sighted_matrix; SEM_data];

                    end
    
                    % Controls - Right field
                    if group_type == 0 && isequal(side_type,'right')
            
                        % Add subject data
                        group_right_matrix = [group_right_matrix; test_data];
                        group_SEM_right_matrix = [group_SEM_right_matrix; SEM_data];

                    % Controls - Left field
                    elseif group_type == 0 && isequal(side_type,'left')
    
                        % Add subject data
                        group_left_matrix = [group_left_matrix; test_data];
                        group_SEM_left_matrix = [group_SEM_left_matrix; SEM_data];

                    end

                end

            end

        end

        %% Group-level analyses

        % Controls
        if group_type == 0

            % Average across subjects
            mean_group_left_matrix = mean(group_left_matrix,1,"omitnan");
            mean_group_right_matrix = mean(group_right_matrix,1,"omitnan");
            mean_group_sighted_matrix = mean(group_sighted_matrix,1,"omitnan");
            mean_group_left_right_matrix = mean(group_left_right_matrix,1,"omitnan");

            % SEM across subjects
            SEM_group_left_matrix = std(group_left_matrix,[],1,"omitnan")/sqrt(size(group_left_matrix,1));
            SEM_group_right_matrix = std(group_right_matrix,[],1,"omitnan")/sqrt(size(group_right_matrix,1));
            SEM_group_sighted_matrix = std(group_sighted_matrix,1,"omitnan")/sqrt(size(group_sighted_matrix,1));
            SEM_group_left_right_matrix = std(group_left_right_matrix,1,"omitnan")/sqrt(size(group_left_right_matrix,1));

            % Rename data
            eval([data_type,'_',event_type,'_group_left_matrix = group_left_matrix;'])
            eval([data_type,'_',event_type,'_group_right_matrix = group_right_matrix;'])
            eval([data_type,'_',event_type,'_group_sighted_matrix = group_sighted_matrix;'])
            eval([data_type,'_',event_type,'_group_left_right_matrix = group_left_right_matrix;'])

            eval([data_type,'_',event_type,'_mean_group_left_matrix = mean_group_left_matrix;'])
            eval([data_type,'_',event_type,'_mean_group_right_matrix = mean_group_right_matrix;'])
            eval([data_type,'_',event_type,'_mean_group_sighted_matrix = mean_group_sighted_matrix;'])
            eval([data_type,'_',event_type,'_mean_group_left_right_matrix = mean_group_left_right_matrix;'])

            eval([data_type,'_',event_type,'_SEM_group_left_matrix = SEM_group_left_matrix;'])
            eval([data_type,'_',event_type,'_SEM_group_right_matrix = SEM_group_right_matrix;'])
            eval([data_type,'_',event_type,'_SEM_group_sighted_matrix = SEM_group_sighted_matrix;'])
            eval([data_type,'_',event_type,'_SEM_group_left_right_matrix = SEM_group_left_right_matrix;'])

        % Patients
        elseif group_type == 1 

            % Average across subjects
            mean_group_sighted_matrix = mean(group_sighted_matrix,1,"omitnan");
            mean_group_blinded_unaware_matrix = mean(group_blinded_unaware_matrix,1,"omitnan");
            mean_group_blinded_aware_matrix = mean(group_blinded_aware_matrix,1,"omitnan");

            % SEM across subjects
            SEM_group_sighted_matrix = std(group_sighted_matrix,[],1,"omitnan")/sqrt(size(group_sighted_matrix,1));
            SEM_group_blinded_unaware_matrix = std(group_blinded_unaware_matrix,[],1,"omitnan")/sqrt(size(group_blinded_unaware_matrix,1));
            SEM_group_blinded_aware_matrix = std(group_blinded_aware_matrix,[],1,"omitnan")/sqrt(size(group_blinded_aware_matrix,1));

            % Rename data
            eval([data_type,'_',event_type,'_group_sighted_matrix = group_sighted_matrix;'])
            eval([data_type,'_',event_type,'_group_blinded_unaware_matrix = group_blinded_unaware_matrix;'])
            eval([data_type,'_',event_type,'_group_blinded_aware_matrix = group_blinded_aware_matrix;'])

            eval([data_type,'_',event_type,'_mean_group_sighted_matrix = mean_group_sighted_matrix;'])
            eval([data_type,'_',event_type,'_mean_group_blinded_unaware_matrix = mean_group_blinded_unaware_matrix;'])
            eval([data_type,'_',event_type,'_mean_group_blinded_aware_matrix = mean_group_blinded_aware_matrix;'])

            eval([data_type,'_',event_type,'_SEM_group_sighted_matrix = SEM_group_sighted_matrix;'])
            eval([data_type,'_',event_type,'_SEM_group_blinded_unaware_matrix = SEM_group_blinded_unaware_matrix;'])
            eval([data_type,'_',event_type,'_SEM_group_blinded_aware_matrix = SEM_group_blinded_aware_matrix;'])

            eval([data_type,'_',event_type,'_group_SEM_sighted_matrix = group_SEM_sighted_matrix;'])
            eval([data_type,'_',event_type,'_group_SEM_blinded_unaware_matrix = group_SEM_blinded_unaware_matrix;'])
            eval([data_type,'_',event_type,'_group_SEM_blinded_aware_matrix = group_SEM_blinded_aware_matrix;'])

        end

        %% Plot Timecourses
        if create_plots == 'y'

            % Controls
            if group_type == 0

                make_plots(group_type, data_type, event_type, group_sighted_matrix, [], group_left_matrix, group_right_matrix,...
                     mean_group_sighted_matrix, [], mean_group_left_matrix, mean_group_right_matrix, SEM_group_left_matrix, SEM_group_right_matrix, SEM_group_sighted_matrix, [])

            % Patients
            elseif group_type == 1

                make_plots(group_type, data_type, event_type, group_sighted_matrix, group_blinded_matrix, [], [],...
                     mean_group_sighted_matrix, mean_group_blinded_matrix, [], [], [], [], SEM_group_sighted_matrix, SEM_group_blinded_matrix)

            end

        end

    end

end

%% Analyze Signals

% Query interval
query_int = 9001:10500;

% X vector
x_vector = 1:length(query_int);

% Data types
data_types = {'pupil','blink','microsaccade'};

% Loop over types
for data = 1:length(data_types)

    disp(['Analyzing ',data_types{data},' data ...'])

    % Initialize variable
    glare_sighted_min = [];
    nonglare_sighted_min = [];
    white_sighted_min = [];
    ISI_nontarget_sighted_min = [];
    nontarget_sighted_min = [];
    iso_sighted_min = [];
    ISI_glare_sighted_min = [];
    ISI_nonglare_sighted_min = [];
    ISI_white_sighted_min = [];
    ISI_iso_sighted_min = [];

    glare_sighted_max = [];
    nonglare_sighted_max = [];
    white_sighted_max = [];
    ISI_nontarget_sighted_max = [];
    nontarget_sighted_max = [];
    iso_sighted_max = [];
    ISI_glare_sighted_max = [];
    ISI_nonglare_sighted_max = [];
    ISI_white_sighted_max = [];
    ISI_iso_sighted_max = [];

    % Patients
    if isequal(group_type,1)

        glare_blinded_unaware_min = [];
        nonglare_blinded_unaware_min = [];
        white_blinded_unaware_min = [];
        nontarget_blinded_unaware_min = [];
        iso_blinded_unaware_min = [];
        ISI_glare_blinded_unaware_min = [];
        ISI_nonglare_blinded_unaware_min = [];
        ISI_white_blinded_unaware_min = [];
        ISI_nontarget_blinded_unaware_min = [];
        ISI_iso_blinded_unaware_min = [];

        glare_blinded_aware_min = [];
        nonglare_blinded_aware_min = [];
        white_blinded_aware_min = [];
        nontarget_blinded_aware_min = [];
        iso_blinded_aware_min = [];
        ISI_glare_blinded_aware_min = [];
        ISI_nonglare_blinded_aware_min = [];
        ISI_white_blinded_aware_min = [];
        ISI_nontarget_blinded_aware_min = [];
        ISI_iso_blinded_aware_min = [];

        glare_blinded_unaware_max = [];
        nonglare_blinded_unaware_max = [];
        white_blinded_unaware_max = [];
        nontarget_blinded_unaware_max = [];
        iso_blinded_unaware_max = [];
        ISI_glare_blinded_unaware_max = [];
        ISI_nonglare_blinded_unaware_max = [];
        ISI_white_blinded_unaware_max = [];
        ISI_nontarget_blinded_unaware_max = [];
        ISI_iso_blinded_unaware_max = [];

        glare_blinded_aware_max = [];
        nonglare_blinded_aware_max = [];
        white_blinded_aware_max = [];
        nontarget_blinded_aware_max = [];
        iso_blinded_aware_max = [];
        ISI_glare_blinded_aware_max = [];
        ISI_nonglare_blinded_aware_max = [];
        ISI_white_blinded_aware_max = [];
        ISI_nontarget_blinded_aware_max = [];
        ISI_iso_blinded_aware_max = [];

    end

    % Define data

    % Patients
    if isequal(group_type,1) 

        glare_sighted_data = eval([data_types{data},'_glare_group_sighted_matrix']);
        nonglare_sighted_data = eval([data_types{data},'_nonglare_group_sighted_matrix']);
        white_sighted_data = eval([data_types{data},'_white_group_sighted_matrix']);
        nontarget_sighted_data = eval([data_types{data},'_nontarget_group_sighted_matrix']);
        iso_sighted_data = eval([data_types{data},'_iso_group_sighted_matrix']);

        ISI_glare_sighted_data = eval([data_types{data},'_ISI_glare_group_sighted_matrix']);
        ISI_nonglare_sighted_data = eval([data_types{data},'_ISI_nonglare_group_sighted_matrix']);
        ISI_white_sighted_data = eval([data_types{data},'_ISI_white_group_sighted_matrix']);
        ISI_nontarget_sighted_data = eval([data_types{data},'_ISI_glare_nonglare_white_iso_group_sighted_matrix']);
        ISI_iso_sighted_data = eval([data_types{data},'_ISI_iso_group_sighted_matrix']);

        glare_blinded_unaware_data = eval([data_types{data},'_glare_group_blinded_unaware_matrix']);
        nonglare_blinded_unaware_data = eval([data_types{data},'_nonglare_group_blinded_unaware_matrix']);
        white_blinded_unaware_data = eval([data_types{data},'_white_group_blinded_unaware_matrix']);
        nontarget_blinded_unaware_data = eval([data_types{data},'_nontarget_group_blinded_unaware_matrix']);
        iso_blinded_unaware_data = eval([data_types{data},'_iso_group_blinded_unaware_matrix']);

        ISI_glare_blinded_unaware_data = eval([data_types{data},'_ISI_glare_group_blinded_unaware_matrix']);
        ISI_nonglare_blinded_unaware_data = eval([data_types{data},'_ISI_nonglare_group_blinded_unaware_matrix']);
        ISI_white_blinded_unaware_data = eval([data_types{data},'_ISI_white_group_blinded_unaware_matrix']);
        ISI_nontarget_blinded_unaware_data = eval([data_types{data},'_ISI_glare_nonglare_white_iso_group_blinded_unaware_matrix']);
        ISI_iso_blinded_unaware_data = eval([data_types{data},'_ISI_iso_group_blinded_unaware_matrix']);

        glare_blinded_aware_data = eval([data_types{data},'_glare_group_blinded_aware_matrix']);
        nonglare_blinded_aware_data = eval([data_types{data},'_nonglare_group_blinded_aware_matrix']);
        white_blinded_aware_data = eval([data_types{data},'_white_group_blinded_aware_matrix']);
        nontarget_blinded_aware_data = eval([data_types{data},'_nontarget_group_blinded_aware_matrix']);
        iso_blinded_aware_data = eval([data_types{data},'_iso_group_blinded_aware_matrix']);

        ISI_glare_blinded_aware_data = eval([data_types{data},'_ISI_glare_group_blinded_aware_matrix']);
        ISI_nonglare_blinded_aware_data = eval([data_types{data},'_ISI_nonglare_group_blinded_aware_matrix']);
        ISI_white_blinded_aware_data = eval([data_types{data},'_ISI_white_group_blinded_aware_matrix']);
        ISI_nontarget_blinded_aware_data = eval([data_types{data},'_ISI_glare_nonglare_white_iso_group_blinded_aware_matrix']);
        ISI_iso_blinded_aware_data = eval([data_types{data},'_ISI_iso_group_blinded_aware_matrix']);

    % Controls
    elseif isequal(group_type,0)

        glare_sighted_data = eval([data_types{data},'_glare_group_left_right_matrix']);
        nonglare_sighted_data = eval([data_types{data},'_nonglare_group_left_right_matrix']);
        white_sighted_data = eval([data_types{data},'_white_group_left_right_matrix']);
        nontarget_sighted_data = eval([data_types{data},'_nontarget_group_left_right_matrix']);
        iso_sighted_data = eval([data_types{data},'_iso_group_left_right_matrix']);

        ISI_glare_sighted_data = eval([data_types{data},'_ISI_glare_group_left_right_matrix']);
        ISI_nonglare_sighted_data = eval([data_types{data},'_ISI_nonglare_group_left_right_matrix']);
        ISI_white_sighted_data = eval([data_types{data},'_ISI_white_group_left_right_matrix']);
        ISI_nontarget_sighted_data = eval([data_types{data},'_ISI_glare_nonglare_white_iso_group_left_right_matrix']);
        ISI_iso_sighted_data = eval([data_types{data},'_ISI_iso_group_left_right_matrix']);

    end

    % Loop over sighted subjects
    for sub = 1:size(pupil_glare_group_sighted_matrix,1)
        
        % Find min and max and add to group variable
        glare_sighted_min = [glare_sighted_min; nanmin(glare_sighted_data(sub, query_int))];
        glare_sighted_max = [glare_sighted_max; nanmax(glare_sighted_data(sub, query_int))];

        nonglare_sighted_min = [nonglare_sighted_min; nanmin(nonglare_sighted_data(sub, query_int))];
        nonglare_sighted_max = [nonglare_sighted_max; nanmax(nonglare_sighted_data(sub, query_int))];

        white_sighted_min = [white_sighted_min; nanmin(white_sighted_data(sub, query_int))];
        white_sighted_max = [white_sighted_max; nanmax(white_sighted_data(sub, query_int))];

        nontarget_sighted_min = [nontarget_sighted_min; nanmin(nontarget_sighted_data(sub, query_int))];
        nontarget_sighted_max = [nontarget_sighted_max; nanmax(nontarget_sighted_data(sub, query_int))];

        iso_sighted_min = [iso_sighted_min; nanmin(iso_sighted_data(sub, query_int))];
        iso_sighted_max = [iso_sighted_max; nanmax(iso_sighted_data(sub, query_int))];

        ISI_glare_sighted_min = [ISI_glare_sighted_min; nanmin(ISI_glare_sighted_data(sub, query_int))];
        ISI_glare_sighted_max = [ISI_glare_sighted_max; nanmax(ISI_glare_sighted_data(sub, query_int))];

        ISI_nonglare_sighted_min = [ISI_nonglare_sighted_min; nanmin(ISI_nonglare_sighted_data(sub, query_int))];
        ISI_nonglare_sighted_max = [ISI_nonglare_sighted_max; nanmax(ISI_nonglare_sighted_data(sub, query_int))];

        ISI_white_sighted_min = [ISI_white_sighted_min; nanmin(ISI_white_sighted_data(sub, query_int))];
        ISI_white_sighted_max = [ISI_white_sighted_max; nanmax(ISI_white_sighted_data(sub, query_int))];

        ISI_nontarget_sighted_min = [ISI_nontarget_sighted_min; nanmin(ISI_nontarget_sighted_data(sub, query_int))];
        ISI_nontarget_sighted_max = [ISI_nontarget_sighted_max; nanmax(ISI_nontarget_sighted_data(sub, query_int))];

        ISI_iso_sighted_min = [ISI_iso_sighted_min; nanmin(ISI_iso_sighted_data(sub, query_int))];
        ISI_iso_sighted_max = [ISI_iso_sighted_max; nanmax(ISI_iso_sighted_data(sub, query_int))];

    end

    % Patients
    if isequal(group_type,1)

        % Loop over blinded unaware subjects
        for sub = 1:size(pupil_glare_group_blinded_unaware_matrix,1)
         
            % Find min and max and add to group variable
            glare_blinded_unaware_min = [glare_blinded_unaware_min; nanmin(glare_blinded_unaware_data(sub, query_int))];
            glare_blinded_unaware_max = [glare_blinded_unaware_max; nanmax(glare_blinded_unaware_data(sub, query_int))];
            
            nonglare_blinded_unaware_min = [nonglare_blinded_unaware_min; nanmin(nonglare_blinded_unaware_data(sub, query_int))];
            nonglare_blinded_unaware_max = [nonglare_blinded_unaware_max; nanmax(nonglare_blinded_unaware_data(sub, query_int))];
            
            white_blinded_unaware_min = [white_blinded_unaware_min; nanmin(white_blinded_unaware_data(sub, query_int))];
            white_blinded_unaware_max = [white_blinded_unaware_max; nanmax(white_blinded_unaware_data(sub, query_int))];
            
            nontarget_blinded_unaware_min = [nontarget_blinded_unaware_min; nanmin(nontarget_blinded_unaware_data(sub, query_int))];
            nontarget_blinded_unaware_max = [nontarget_blinded_unaware_max; nanmax(nontarget_blinded_unaware_data(sub, query_int))];
            
            iso_blinded_unaware_min = [iso_blinded_unaware_min; nanmin(iso_blinded_unaware_data(sub, query_int))];
            iso_blinded_unaware_max = [iso_blinded_unaware_max; nanmax(iso_blinded_unaware_data(sub, query_int))];
            
            ISI_glare_blinded_unaware_min = [ISI_glare_blinded_unaware_min; nanmin(ISI_glare_blinded_unaware_data(sub, query_int))];
            ISI_glare_blinded_unaware_max = [ISI_glare_blinded_unaware_max; nanmax(ISI_glare_blinded_unaware_data(sub, query_int))];
    
            ISI_nonglare_blinded_unaware_min = [ISI_nonglare_blinded_unaware_min; nanmin(ISI_nonglare_blinded_unaware_data(sub, query_int))];
            ISI_nonglare_blinded_unaware_max = [ISI_nonglare_blinded_unaware_max; nanmax(ISI_nonglare_blinded_unaware_data(sub, query_int))];
    
            ISI_white_blinded_unaware_min = [ISI_white_blinded_unaware_min; nanmin(ISI_white_blinded_unaware_data(sub, query_int))];
            ISI_white_blinded_unaware_max = [ISI_white_blinded_unaware_max; nanmax(ISI_white_blinded_unaware_data(sub, query_int))];
            
            ISI_nontarget_blinded_unaware_min = [ISI_nontarget_blinded_unaware_min; nanmin(ISI_nontarget_blinded_unaware_data(sub, query_int))];
            ISI_nontarget_blinded_unaware_max = [ISI_nontarget_blinded_unaware_max; nanmax(ISI_nontarget_blinded_unaware_data(sub, query_int))];
            
            ISI_iso_blinded_unaware_min = [ISI_iso_blinded_unaware_min; nanmin(ISI_iso_blinded_unaware_data(sub, query_int))];
            ISI_iso_blinded_unaware_max = [ISI_iso_blinded_unaware_max; nanmax(ISI_iso_blinded_unaware_data(sub, query_int))];
            

        end

        % Loop over blinded aware subjects
        for sub = 1:size(pupil_glare_group_blinded_aware_matrix,1)
    
            % Find min and max and add to group variable
            glare_blinded_aware_min = [glare_blinded_aware_min; nanmin(glare_blinded_aware_data(sub, query_int))];
            glare_blinded_aware_max = [glare_blinded_aware_max; nanmax(glare_blinded_aware_data(sub, query_int))];
            
            nonglare_blinded_aware_min = [nonglare_blinded_aware_min; nanmin(nonglare_blinded_aware_data(sub, query_int))];
            nonglare_blinded_aware_max = [nonglare_blinded_aware_max; nanmax(nonglare_blinded_aware_data(sub, query_int))];
            
            white_blinded_aware_min = [white_blinded_aware_min; nanmin(white_blinded_aware_data(sub, query_int))];
            white_blinded_aware_max = [white_blinded_aware_max; nanmax(white_blinded_aware_data(sub, query_int))];
            
            nontarget_blinded_aware_min = [nontarget_blinded_aware_min; nanmin(nontarget_blinded_aware_data(sub, query_int))];
            nontarget_blinded_aware_max = [nontarget_blinded_aware_max; nanmax(nontarget_blinded_aware_data(sub, query_int))];
    
            iso_blinded_aware_min = [iso_blinded_aware_min; nanmin(iso_blinded_aware_data(sub, query_int))];
            iso_blinded_aware_max = [iso_blinded_aware_max; nanmax(iso_blinded_aware_data(sub, query_int))];
    
            ISI_glare_blinded_aware_min = [ISI_glare_blinded_aware_min; nanmin(ISI_glare_blinded_aware_data(sub, query_int))];
            ISI_glare_blinded_aware_max = [ISI_glare_blinded_aware_max; nanmax(ISI_glare_blinded_aware_data(sub, query_int))];
    
            ISI_nonglare_blinded_aware_min = [ISI_nonglare_blinded_aware_min; nanmin(ISI_nonglare_blinded_aware_data(sub, query_int))];
            ISI_nonglare_blinded_aware_max = [ISI_nonglare_blinded_aware_max; nanmax(ISI_nonglare_blinded_aware_data(sub, query_int))];
    
            ISI_white_blinded_aware_min = [ISI_white_blinded_aware_min; nanmin(ISI_white_blinded_aware_data(sub, query_int))];
            ISI_white_blinded_aware_max = [ISI_white_blinded_aware_max; nanmax(ISI_white_blinded_aware_data(sub, query_int))];

            ISI_nontarget_blinded_aware_min = [ISI_nontarget_blinded_aware_min; nanmin(ISI_nontarget_blinded_aware_data(sub, query_int))];
            ISI_nontarget_blinded_aware_max = [ISI_nontarget_blinded_aware_max; nanmax(ISI_nontarget_blinded_aware_data(sub, query_int))];            

            ISI_iso_blinded_aware_min = [ISI_iso_blinded_aware_min; nanmin(ISI_iso_blinded_aware_data(sub, query_int))];
            ISI_iso_blinded_aware_max = [ISI_iso_blinded_aware_max; nanmax(ISI_iso_blinded_aware_data(sub, query_int))];            


        end

    end

    % Sighted

    % Calculate SEM for min values
    glare_sighted_min_sem = nanstd(glare_sighted_min) / sqrt(sum(~isnan(glare_sighted_min)));
    nonglare_sighted_min_sem = nanstd(nonglare_sighted_min) / sqrt(sum(~isnan(nonglare_sighted_min)));
    white_sighted_min_sem = nanstd(white_sighted_min) / sqrt(sum(~isnan(white_sighted_min)));
    ISI_nontarget_sighted_min_sem = nanstd(ISI_nontarget_sighted_min) / sqrt(sum(~isnan(ISI_nontarget_sighted_min)));
    nontarget_sighted_min_sem = nanstd(nontarget_sighted_min) / sqrt(sum(~isnan(nontarget_sighted_min)));
    
    % Calculate SEM for max values
    glare_sighted_max_sem = nanstd(glare_sighted_max) / sqrt(sum(~isnan(glare_sighted_max)));
    nonglare_sighted_max_sem = nanstd(nonglare_sighted_max) / sqrt(sum(~isnan(nonglare_sighted_max)));
    white_sighted_max_sem = nanstd(white_sighted_max) / sqrt(sum(~isnan(white_sighted_max)));
    ISI_nontarget_sighted_max_sem = nanstd(ISI_nontarget_sighted_max) / sqrt(sum(~isnan(ISI_nontarget_sighted_max)));
    nontarget_sighted_max_sem = nanstd(nontarget_sighted_max) / sqrt(sum(~isnan(nontarget_sighted_max)));

    % Patients
    if isequal(group_type,1) 

        % Blinded unaware
    
        % Calculate SEM for min values
        glare_blinded_unaware_min_sem = nanstd(glare_blinded_unaware_min) / sqrt(length(glare_blinded_unaware_min));
        nonglare_blinded_unaware_min_sem = nanstd(nonglare_blinded_unaware_min) / sqrt(length(nonglare_blinded_unaware_min));
        white_blinded_unaware_min_sem = nanstd(white_blinded_unaware_min) / sqrt(length(white_blinded_unaware_min));
        ISI_nontarget_blinded_unaware_min_sem = nanstd(ISI_nontarget_blinded_unaware_min) / sqrt(length(ISI_nontarget_blinded_unaware_min));
        nontarget_blinded_unaware_min_sem = nanstd(nontarget_blinded_unaware_min) / sqrt(length(nontarget_blinded_unaware_min));
        
        % Calculate SEM for max values
        glare_blinded_unaware_max_sem = nanstd(glare_blinded_unaware_max) / sqrt(length(glare_blinded_unaware_max));
        nonglare_blinded_unaware_max_sem = nanstd(nonglare_blinded_unaware_max) / sqrt(length(nonglare_blinded_unaware_max));
        white_blinded_unaware_max_sem = nanstd(white_blinded_unaware_max) / sqrt(length(white_blinded_unaware_max));
        ISI_nontarget_blinded_unaware_max_sem = nanstd(ISI_nontarget_blinded_unaware_max) / sqrt(length(ISI_nontarget_blinded_unaware_max));
        nontarget_blinded_unaware_max_sem = nanstd(nontarget_blinded_unaware_max) / sqrt(length(nontarget_blinded_unaware_max));
    
        % Blinded aware
    
        % Calculate SEM for min values
        glare_blinded_aware_min_sem = nanstd(glare_blinded_aware_min) / sqrt(length(glare_blinded_aware_min));
        nonglare_blinded_aware_min_sem = nanstd(nonglare_blinded_aware_min) / sqrt(length(nonglare_blinded_aware_min));
        white_blinded_aware_min_sem = nanstd(white_blinded_aware_min) / sqrt(length(white_blinded_aware_min));
        ISI_nontarget_blinded_aware_min_sem = nanstd(ISI_nontarget_blinded_aware_min) / sqrt(length(ISI_nontarget_blinded_aware_min));
        nontarget_blinded_aware_min_sem = nanstd(nontarget_blinded_aware_min) / sqrt(length(nontarget_blinded_aware_min));
        
        % Calculate SEM for max values
        glare_blinded_aware_max_sem = nanstd(glare_blinded_aware_max) / sqrt(length(glare_blinded_aware_max));
        nonglare_blinded_aware_max_sem = nanstd(nonglare_blinded_aware_max) / sqrt(length(nonglare_blinded_aware_max));
        white_blinded_aware_max_sem = nanstd(white_blinded_aware_max) / sqrt(length(white_blinded_aware_max));
        ISI_nontarget_blinded_aware_max_sem = nanstd(ISI_nontarget_blinded_aware_max) / sqrt(length(ISI_nontarget_blinded_aware_max));
        nontarget_blinded_aware_max_sem = nanstd(nontarget_blinded_aware_max) / sqrt(length(nontarget_blinded_aware_max));

    end

    %% Plot Min/Max Results
    
    % Plot Mean with SEM error bars
    figure
    hold on
    title([group_name,' - Sighted - ',data_types{data}])
    ylabel(data_types{data})
    
    % Axis parameters
    if isequal(data_types{data},'pupil')

        ylim([-110 40])
        yticks([-90:30:30])

    elseif isequal(data_types{data},'blink')
        
        ylim([0 0.25])

    elseif isequal(data_types{data},'microsaccade')

        ylim([0 0.1])

    end
    
    % Mean values
    mean_values = [mean(ISI_nontarget_sighted_min), mean(white_sighted_min), mean(glare_sighted_min), mean(nonglare_sighted_min)]; 

    % SEM values
    sem_values = [ISI_nontarget_sighted_min_sem, white_sighted_min_sem, glare_sighted_min_sem, nonglare_sighted_min_sem];

    % X positions of the bars
    x_pos = 1:4;
    
    % Bar plot with error bars
    bar(x_pos, mean_values, 'FaceColor', 'flat')
    errorbar(x_pos, mean_values, sem_values, 'k', 'LineStyle', 'none')  % Add SEM as error bars

    % Patients
    if isequal(group_type,1) 

        % Plot Mean with SEM error bars
        figure
        hold on
        title(['Patients - Blinded unaware - ',data_types{data}])
        ylabel(data_types{data})
        
        % Axis parameters
        if isequal(data_types{data},'pupil')

            ylim([-110 40])
            yticks([-90:30:30])

        elseif isequal(data_types{data},'blink')
            
            ylim([0 0.25])
    
        elseif isequal(data_types{data},'microsaccade')
    
            ylim([0 0.1])

        end
        
        % Mean values
        mean_values = [mean(ISI_nontarget_blinded_unaware_min), mean(white_blinded_unaware_min), mean(glare_blinded_unaware_min), mean(nonglare_blinded_unaware_min)];
        
        % SEM values
        sem_values = [ISI_nontarget_blinded_unaware_min_sem, white_blinded_unaware_min_sem, glare_blinded_unaware_min_sem, nonglare_blinded_unaware_min_sem];
       
        % X positions of the bars
        x_pos = 1:4;
        
        % Bar plot with error bars
        bar(x_pos, mean_values, 'FaceColor', 'flat')
        errorbar(x_pos, mean_values, sem_values, 'k', 'LineStyle', 'none')  % Add SEM as error bars

        % Plot Mean with SEM error bars
        figure
        hold on
        title(['Patients - Blinded aware - ',data_types{data}])
        ylabel(data_types{data})
        
        % Axis parameters
        if isequal(data_types{data},'pupil')

            ylim([-110 40])
            yticks([-90:30:30])

        elseif isequal(data_types{data},'blink')
            
            ylim([0 0.25])
    
        elseif isequal(data_types{data},'microsaccade')
    
            ylim([0 0.1])

        end
        
        % Mean values
        mean_values = [mean(ISI_nontarget_blinded_aware_min), mean(white_blinded_aware_min), mean(glare_blinded_aware_min), mean(nonglare_blinded_aware_min)];

        % SEM values
        sem_values = [ISI_nontarget_blinded_aware_min_sem, white_blinded_aware_min_sem, glare_blinded_aware_min_sem, nonglare_blinded_aware_min_sem];
        
        % X positions of the bars
        x_pos = 1:4;
        
        % Bar plot with error bars
        bar(x_pos, mean_values, 'FaceColor', 'flat')
        errorbar(x_pos, mean_values, sem_values, 'k', 'LineStyle', 'none')  % Add SEM as error bars

    end
       
    %% Statistical Tests
    
    % Combine data
    %ISI_nontarget_sighted_max_concat = [ISI_white_sighted_max;ISI_glare_sighted_max;ISI_nonglare_sighted_max;ISI_iso_sighted_max];
    %nontarget_sighted_max_concat = [white_sighted_max;glare_sighted_max;nonglare_sighted_max;iso_sighted_max];
    %ISI_nontarget_sighted_min_concat = [ISI_white_sighted_min;ISI_glare_sighted_min;ISI_nonglare_sighted_min;ISI_iso_sighted_min];
    %nontarget_sighted_min_concat = [white_sighted_min;glare_sighted_min;nonglare_sighted_min;iso_sighted_min];
    %nontarget_sighted_min_concat = [white_sighted_min,glare_sighted_min,nonglare_sighted_min];
    white_glare_nonglare_sighted_min_concat = [white_sighted_min,glare_sighted_min,nonglare_sighted_min];
    %white_glare_nonglare_sighted_min_concat = white_glare_nonglare_sighted_min_concat-repmat(mean(white_glare_nonglare_sighted_min_concat,2),1,3);
    
    white_glare_nonglare_mean_sighted_min = mean(white_glare_nonglare_sighted_min_concat,1);
    white_sem_sighted_min = nanstd(white_glare_nonglare_sighted_min_concat(:,1)) / sqrt(size(white_glare_nonglare_sighted_min_concat,1));
    glare_sem_sighted_min = nanstd(white_glare_nonglare_sighted_min_concat(:,2)) / sqrt(size(white_glare_nonglare_sighted_min_concat,1));
    nonglare_sem_sighted_min = nanstd(white_glare_nonglare_sighted_min_concat(:,3)) / sqrt(size(white_glare_nonglare_sighted_min_concat,1));
    white_glare_nonglare_sem_sighted_min = [white_sem_sighted_min,glare_sem_sighted_min,nonglare_sem_sighted_min];

    % Analyze slope across subjects

    % Number of subjects
    num_sub = size(white_glare_nonglare_sighted_min_concat, 1);
    
    % Independent variable (timepoints or condition indices)
    x = [1 2 3]';
    
    % Preallocate slope array
    all_sub_slopes = zeros(num_sub,1);
    
    % Compute slope for each subject
    for sub = 1:num_sub

        % Extract subject data
        sub_data = white_glare_nonglare_sighted_min_concat(sub,:)';  
        
        % Linear fit: p(1) is slope
        slope = polyfit(x, sub_data, 1);  
        
        % Store slope info
        all_sub_slopes(sub) = slope(1);

    end
    
    % Perform test of slopes against 0 - if greater than zero
    p_value = signrank(all_sub_slopes,0,'tail','right');

    % Rename variable
    eval(['p_min_slope_sighted_white_glare_nonglare_',data_types{data},' = p_value;'])

    % % Run t-test
    % [h,p_max_sighted_ISI_vs_nontarget,ci,stats_max_sighted_ISI_vs_nontarget] = ttest(ISI_nontarget_sighted_max_concat,nontarget_sighted_max_concat);
    % [h,p_min_sighted_ISI_vs_nontarget,ci,stats_min_sighted_ISI_vs_nontarget] = ttest(ISI_nontarget_sighted_min_concat,nontarget_sighted_min_concat);
    % 
    % % Run Wilcoxon signed rank test
    % [p_max_rank_sighted] = signrank(nontarget_sighted_max_concat, ISI_nontarget_sighted_max_concat);
    % [p_min_rank_sighted] = signrank(nontarget_sighted_min_concat, ISI_nontarget_sighted_min_concat);

    % Rename variables
    % eval(['p_max_sighted_ISI_vs_nontarget_',data_types{data},' = p_max_sighted_ISI_vs_nontarget;'])
    % eval(['p_min_sighted_ISI_vs_nontarget_',data_types{data},' = p_min_sighted_ISI_vs_nontarget;'])
    % 
    % eval(['stats_max_sighted_ISI_vs_nontarget_',data_types{data},' = stats_max_sighted_ISI_vs_nontarget;'])
    % eval(['stats_min_sighted_ISI_vs_nontarget_',data_types{data},' = stats_min_sighted_ISI_vs_nontarget;'])
    % 
    % eval(['p_max_sighted_ISI_vs_nontarget_',data_types{data},' = p_max_rank_sighted;'])
    % eval(['p_min_sighted_ISI_vs_nontarget_',data_types{data},' = p_min_rank_sighted;'])

    % Plot subject slope responses
    timevector = [1,2,3];

    % Setup figure
    figure
    hold on

    % Figure parameters
    if isequal(group_type,0)

        title('Control - Sighted')

        yticks([-250:50:50])
        ylim([-275 50])
    
    else

        title('Patient - Sighted')

        yticks([-150:50:50])
        ylim([-150 50])
    

    end

    xlabel('Stimulus type [white glare nonglare]')
    xticks([1 2 3])
    ylabel('Pupil size')
    xlim([0.75 3.25])

    % Plot timecourses
    plot(timevector,white_glare_nonglare_sighted_min_concat','k')
    scatter(timevector,white_glare_nonglare_sighted_min_concat','k','filled')
    plot(timevector,white_glare_nonglare_mean_sighted_min,'r')
    plot(timevector,white_glare_nonglare_mean_sighted_min+white_glare_nonglare_sem_sighted_min,'--r')
    plot(timevector,white_glare_nonglare_mean_sighted_min-white_glare_nonglare_sem_sighted_min,'--r')

    % Patients
    if isequal(group_type,1) 
    
        % Combine data - blind unaware
        %ISI_nontarget_blinded_unaware_max_concat = [ISI_white_blinded_unaware_max;ISI_glare_blinded_unaware_max;ISI_nonglare_blinded_unaware_max;ISI_iso_blinded_unaware_max];
        %nontarget_blinded_unaware_max_concat = [white_blinded_unaware_max;glare_blinded_unaware_max;nonglare_blinded_unaware_max;iso_blinded_unaware_max];
        %ISI_nontarget_blinded_unaware_min_concat = [ISI_white_blinded_unaware_min;ISI_glare_blinded_unaware_min;ISI_nonglare_blinded_unaware_min;ISI_iso_blinded_unaware_min];
        %nontarget_blinded_unaware_min_concat = [white_blinded_unaware_min;glare_blinded_unaware_min;nonglare_blinded_unaware_min;iso_blinded_unaware_min];
        white_glare_nonglare_blinded_unaware_min_concat = [white_blinded_unaware_min,glare_blinded_unaware_min,nonglare_blinded_unaware_min];
        %white_glare_nonglare_blinded_unaware_min_concat = white_glare_nonglare_blinded_unaware_min_concat-repmat(mean(white_glare_nonglare_blinded_unaware_min_concat,2),1,3);

        white_glare_nonglare_mean_blinded_unaware_min = mean(white_glare_nonglare_blinded_unaware_min_concat,1);
        white_sem_blinded_unaware_min = nanstd(white_glare_nonglare_blinded_unaware_min_concat(:,1)) / sqrt(size(white_glare_nonglare_blinded_unaware_min_concat,1));
        glare_sem_blinded_unaware_min = nanstd(white_glare_nonglare_blinded_unaware_min_concat(:,2)) / sqrt(size(white_glare_nonglare_blinded_unaware_min_concat,1));
        nonglare_sem_blinded_unaware_min = nanstd(white_glare_nonglare_blinded_unaware_min_concat(:,3)) / sqrt(size(white_glare_nonglare_blinded_unaware_min_concat,1));
        white_glare_nonglare_sem_blinded_unaware_min = [white_sem_blinded_unaware_min,glare_sem_blinded_unaware_min,nonglare_sem_blinded_unaware_min];

        % Combine data - blind aware
        %ISI_nontarget_blinded_aware_max_concat = [ISI_white_blinded_aware_max;ISI_glare_blinded_aware_max;ISI_nonglare_blinded_aware_max;ISI_iso_blinded_aware_max];
        %nontarget_blinded_aware_max_concat = [white_blinded_aware_max;glare_blinded_aware_max;nonglare_blinded_aware_max;iso_blinded_aware_max];
        %ISI_nontarget_blinded_aware_min_concat = [ISI_white_blinded_aware_min;ISI_glare_blinded_aware_min;ISI_nonglare_blinded_aware_min;ISI_iso_blinded_aware_min];
        %nontarget_blinded_aware_min_concat = [white_blinded_aware_min;glare_blinded_aware_min;nonglare_blinded_aware_min;iso_blinded_aware_min];
        white_glare_nonglare_blinded_aware_min_concat = [white_blinded_aware_min,glare_blinded_aware_min,nonglare_blinded_aware_min];
        %white_glare_nonglare_blinded_aware_min_concat = white_glare_nonglare_blinded_aware_min_concat-repmat(mean(white_glare_nonglare_blinded_aware_min_concat,2),1,3);

        white_glare_nonglare_mean_blinded_aware_min = mean(white_glare_nonglare_blinded_aware_min_concat,1);
        white_sem_blinded_aware_min = nanstd(white_glare_nonglare_blinded_aware_min_concat(:,1)) / sqrt(size(white_glare_nonglare_blinded_aware_min_concat,1));
        glare_sem_blinded_aware_min = nanstd(white_glare_nonglare_blinded_aware_min_concat(:,2)) / sqrt(size(white_glare_nonglare_blinded_aware_min_concat,1));
        nonglare_sem_blinded_aware_min = nanstd(white_glare_nonglare_blinded_aware_min_concat(:,3)) / sqrt(size(white_glare_nonglare_blinded_aware_min_concat,1));
        white_glare_nonglare_sem_blinded_aware_min = [white_sem_blinded_aware_min,glare_sem_blinded_aware_min,nonglare_sem_blinded_aware_min];

        % Loop over blind fields
        for field = {'aware','unaware'}

            % Define data
            all_sub_data = eval(['white_glare_nonglare_blinded_',cell2mat(field),'_min_concat']);
            mean_data = eval(['white_glare_nonglare_mean_blinded_',cell2mat(field),'_min']);
            sem_data = eval(['white_glare_nonglare_sem_blinded_',cell2mat(field),'_min']);

            % Number of subjects
            num_sub = size(all_sub_data, 1);
            
            % Independent variable (timepoints or condition indices)
            x = [1 2 3]';
            
            % Preallocate slope array
            all_sub_slopes = zeros(num_sub,1);
            
            % Compute slope for each subject
            for sub = 1:num_sub
        
                % Extract subject data
                sub_data = all_sub_data(sub,:)';  
                
                % Linear fit: p(1) is slope
                slope = polyfit(x, sub_data, 1);  
                
                % Store slope info
                all_sub_slopes(sub) = slope(1);
        
            end
            
            % Perform test of slopes against 0 - if greater than zero
            p_value = signrank(all_sub_slopes,0,'tail','right');
        
            % Rename variable
            eval(['p_min_slope_blinded_',cell2mat(field),'_white_glare_nonglare_',data_types{data},' = p_value;'])

            % Plot subject slope responses
            timevector = [1,2,3];
        
            % Setup figure
            figure
            hold on
        
            % Figure parameters
            title(['Patient - Blind ',cell2mat(field)])
            xlabel('Stimulus type [white glare nonglare]')
            xticks([1 2 3])
            ylabel('Pupil size')
            yticks([-150:50:50])
        
            ylim([-150 50])
            xlim([0.75 3.25])
        
            % Plot timecourses
            plot(timevector,all_sub_data','k')
            scatter(timevector,all_sub_data','k','filled')
            plot(timevector,mean_data,'r')
            plot(timevector,mean_data+sem_data,'--r')
            plot(timevector,mean_data-sem_data,'--r')

        end
        
        % % Run t-test
        % [h,p_max_blinded_unaware_ISI_vs_nontarget,ci,stats_max_blinded_unaware_ISI_vs_nontarget] = ttest(ISI_nontarget_blinded_unaware_max_concat,nontarget_blinded_unaware_max_concat);
        % [h,p_min_blinded_unaware_ISI_vs_nontarget,ci,stats_min_blinded_unaware_ISI_vs_nontarget] = ttest(ISI_nontarget_blinded_unaware_min_concat,nontarget_blinded_unaware_min_concat);
        % 
        % [h,p_max_blinded_aware_ISI_vs_nontarget,ci,stats_max_blinded_aware_ISI_vs_nontarget] = ttest(ISI_nontarget_blinded_aware_max_concat,nontarget_blinded_aware_max_concat);
        % [h,p_min_blinded_aware_ISI_vs_nontarget,ci,stats_min_blinded_aware_ISI_vs_nontarget] = ttest(ISI_nontarget_blinded_aware_min_concat,nontarget_blinded_aware_min_concat);
        % 
        % % Run Wilcoxon signed rank test
        % [p_max_rank_blinded_aware] = signrank(nontarget_blinded_aware_max_concat, ISI_nontarget_blinded_aware_max_concat);
        % [p_min_rank_blinded_aware] = signrank(nontarget_blinded_aware_min_concat, ISI_nontarget_blinded_aware_min_concat);
        % [p_max_rank_blinded_unaware] = signrank(nontarget_blinded_unaware_max_concat, ISI_nontarget_blinded_unaware_max_concat);
        % [p_min_rank_blinded_unaware] = signrank(nontarget_blinded_unaware_min_concat, ISI_nontarget_blinded_unaware_min_concat);
        % 
        % % Rename variables
        % eval(['p_max_blinded_aware_ISI_vs_nontarget_',data_types{data},' = p_max_blinded_aware_ISI_vs_nontarget;'])
        % eval(['p_min_blinded_aware_ISI_vs_nontarget_',data_types{data},' = p_min_blinded_aware_ISI_vs_nontarget;'])
        % eval(['p_max_blinded_unaware_ISI_vs_nontarget_',data_types{data},' = p_max_blinded_unaware_ISI_vs_nontarget;'])
        % eval(['p_min_blinded_unaware_ISI_vs_nontarget_',data_types{data},' = p_min_blinded_unaware_ISI_vs_nontarget;'])
        % 
        % eval(['stats_max_blinded_aware_ISI_vs_nontarget_',data_types{data},' = stats_max_blinded_aware_ISI_vs_nontarget;'])
        % eval(['stats_min_blinded_aware_ISI_vs_nontarget_',data_types{data},' = stats_min_blinded_aware_ISI_vs_nontarget;'])
        % eval(['stats_max_blinded_unaware_ISI_vs_nontarget_',data_types{data},' = stats_max_blinded_unaware_ISI_vs_nontarget;'])
        % eval(['stats_min_blinded_unaware_ISI_vs_nontarget_',data_types{data},' = stats_min_blinded_unaware_ISI_vs_nontarget;'])
        % 
        % eval(['p_max_blinded_aware_ISI_vs_nontarget_',data_types{data},' = p_max_rank_blinded_aware;'])
        % eval(['p_min_blinded_aware_ISI_vs_nontarget_',data_types{data},' = p_min_rank_blinded_aware;'])
        % eval(['p_max_blinded_unaware_ISI_vs_nontarget_',data_types{data},' = p_max_rank_blinded_unaware;'])
        % eval(['p_min_blinded_unaware_ISI_vs_nontarget_',data_types{data},' = p_min_rank_blinded_unaware;'])

    end
  
    %% Save min/max pupil values
    
    % Output directory
    cd(output_dir)

    % Patients
    if isequal(group_type,1)
    
        save([data_types{data},'_patients_stat_results.mat'],'ISI_nontarget_sighted*','white_sighted*','glare_sighted*','nonglare_sighted*',"nontarget_sighted*",...
            "ISI_nontarget_blinded*", "white_blinded*","glare_blinded*","nonglare_blinded*","nontarget_blinded*",...
            "ISI_glare*","ISI_nonglare*","ISI_white*",'query_int',['p_*',data_types{data}]);

    % Controls
    else

        save([data_types{data},'_controls_stat_results.mat'],'ISI_nontarget_sighted*','white_sighted*','glare_sighted*','nonglare_sighted*',"nontarget_sighted*",...
            'ISI_glare_sighted*','ISI_nonglare_sighted*','ISI_white_sighted*','query_int',['p_*',data_types{data}]);

    end
      
    
end

%% Plot Multiple Conditions with Stats

% Color list
color_list = {'k','b','c','m','y'};

% Define data types
data_list = {'pupil','blink','microsaccade'};

% Define event types
%group_list = {{'ISI_glare_nonglare_white','glare','nonglare','white'};{'ISI_distractor','distractor'};{'ISI_glare_nonglare_white','nontarget'}};
group_list = {{'ISI_distractor','distractor'};{'ISI_glare_nonglare_white_iso','nontarget'};{'ISI_glare_nonglare_white','glare','nonglare','white'}};

% Comparison name
%comp_name = {'ISI vs Other stimuli','ISI distractor vs Distractor','ISI nontarget vs nontarget'};
comp_name = {'ISI distractor vs Distractor','ISI nontarget vs nontarget','ISI vs Other stimuli'};

% Timevector
timevector = [-9000:9000];

% Define sides

% Controls
if isequal(group_type,0)

    side_list = {'left_right'};

% Patients
else isequal(group_type,1)
    
    side_list = {'sighted','blinded_unaware','blinded_aware'};

end

% Group list
for list = 1:size(group_list,1)

    % Select list of events
    event_list = group_list{list};

    % Loop over sides
    for side = 1:length(side_list)        
    
        % Select side
        side_type = side_list{side};
    
        % Loop over data type
        for data = 1:length(data_list)
        
            % Define data type
            data_type = data_list{data};
    
            % Setup plot
            fig = figure
            set(fig,'renderer','Painters')
            hold on
    
            % Figure parameters

            % Pupil
            if isequal(data_type,'pupil')
    
                % Axis limits
                if any(ismember(event_list,'distractor'))

                    ymin = -160;
                    ymax = 400;
                    yticks([-100:100:400])

                else

                    ymin = -110;
                    ymax = 40;
                    yticks([-90,-60,-30,0,30])

                end
                
                % X axis parameters
                xmin = -500;
                xmax = 6000;
                xticks([0:1500:6000])
    
                % Stats y axis
                current_yaxis = 10;
    
                % Y label
                ylabel('Pupil Diameter')
    
            % Blink
            elseif isequal(data_type,'blink')
    
                % Axis limits
                if any(ismember(event_list,'distractor'))

                    ymin = 0;
                    ymax = 0.35;

                else

                    ymin = 0;
                    ymax = 0.22;
                    yticks([ymin:0.05:ymax])

                end
                
                % X axis parameters
                xmin = -500;
                xmax = 6000;
                xticks([0:1500:6000])

                % Stats y axis
                current_yaxis = 0.1;
    
                % Y label
                ylabel('Blink Fraction')
    
            % Microsaccade
            elseif isequal(data_type,'microsaccade')
    
                % Axis limits
                if any(ismember(event_list,'distractor'))
    
                    ymin = 0;
                    ymax = 0.105;
                    yticks([0:0.02:0.1])

                else
    
                    ymin = 0.02;
                    ymax = 0.P2;
                    yticks([ymin:0.02:ymax])

                end
                
                % X axis parameters
                xmin = -500;
                xmax = 6000;
                xticks([0:1500:6000])

                % Stats y axis
                current_yaxis = 0.05;
    
                % Y label
                ylabel('Microsaccade Fraction')
    
            end
            
            % Figure headings
            title([comp_name{list}, ' - ', group_name,' - ',side_type,' - ',data_type], "Interpreter","none")
            xlabel('Time (ms)')
        
            % Axis limits
            xlim([xmin xmax])
            ylim([ymin ymax])
        
            % Stimulus times
            plot([0 0],[ymin ymax],'k')
            plot([3000 3000],[ymin ymax],'k')
        
            % Loop over event types
            for type = 1:length(event_list)
        
                % Define event type
                event_type = event_list{type};
    
                % Define color
                current_color = color_list{type};
    
                % Current data
                current_mean_timecourse = eval([data_type,'_',event_type,'_mean_group_',side_type,'_matrix']);
                current_SEM_timecourse = eval([data_type,'_',event_type,'_SEM_group_',side_type,'_matrix']);
    
                % Plot data
                plot(timevector,current_mean_timecourse,color_list{type},'LineWidth',1)
                plot(timevector,current_mean_timecourse+current_SEM_timecourse,current_color)
                plot(timevector,current_mean_timecourse-current_SEM_timecourse,current_color)
    
            end

            % Plot stats
            try

            plot_stats(group_name,output_dir,data_type,side_type,event_list,current_color,current_yaxis)

            end

        end
    
    end

end

%% Plot Stats

function plot_stats(group_name,output_dir,data_type,side_type,event_list,current_color,current_yaxis)

    % Epoch center time
    event_time = 9001;

    % Load statistics
    try

        load(fullfile(output_dir,[group_name,'_',data_type,'_timecourse_perm_results_',side_type,'_',event_list{2},'_vs_',event_list{1},'.mat']),'sig_time_pts');

    catch
    
        error('No stats found!')        

    end

    % Plot statistically significant times
    
    % If there are significant times points
    if not(isempty(sig_time_pts))
    
        % Find significant break points
        sig_breaks = find(diff(sig_time_pts) > 1);
    
        % If there breaks in sig times
        if not(isempty(sig_breaks))
            
            % Loop over discontinuous points
            for breaks = 1:length(sig_breaks)
    
                % Current break point
                break_point = sig_breaks(breaks);
    
                % First break
                if breaks == 1 
    
                    plot((sig_time_pts(1:break_point)-event_time),ones(1,length(sig_time_pts(1:break_point)))*current_yaxis, 'Color', current_color, 'LineWidth',2)
    
                    % If only one break point also plot to the end of sig times
                    if length(sig_breaks) == 1
    
                        % Between last break and end
                        plot([sig_time_pts(break_point+1:length(sig_time_pts))]-event_time,ones(1,length(sig_time_pts(break_point+1:length(sig_time_pts))))*current_yaxis, 'Color', current_color, 'LineWidth',2)
    
                    end
    
                % Last break
                elseif breaks == length(sig_breaks)
    
                    % Between penultimate and final break
                    plot([sig_time_pts(sig_breaks(breaks-1)+1):sig_time_pts(break_point)]-event_time,...
                        ones(1,length((sig_time_pts(sig_breaks(breaks-1)+1):sig_time_pts(break_point))))*current_yaxis, 'Color', current_color, 'LineWidth',2)
    
                    % Between last break and end
                    plot([sig_time_pts(break_point+1:length(sig_time_pts))]-event_time,ones(1,length(sig_time_pts(break_point+1:length(sig_time_pts))))*current_yaxis, 'Color', current_color, 'LineWidth',2)
    
                % Middle breaks
                else
    
                    plot([sig_time_pts(sig_breaks(breaks-1)+1):sig_time_pts(break_point)]-event_time,...
                        ones(1,length((sig_time_pts(sig_breaks(breaks-1)+1):sig_time_pts(break_point))))*current_yaxis, 'Color', current_color, 'LineWidth',2)
    
                end
    
            end
        
        % If the significant time points are continuous
        else
    
          % Plot significance line
          plot(sig_time_pts-event_time, ones(1,length(sig_time_pts))*current_yaxis, 'Color', current_color, 'LineWidth',5)
        
        end
        
    end

end

%% Visualize Data

function make_plots(group_type, data_type, event_type, group_sighted_matrix, group_blinded_matrix, group_left_matrix, group_right_matrix,...
    mean_group_sighted_matrix, mean_group_blinded_matrix, mean_group_left_matrix, mean_group_right_matrix,...
    SEM_group_left_matrix, SEM_group_right_matrix, SEM_group_sighted_matrix, SEM_group_blinded_matrix)

    % Plot parameters

    % Setup figure setting
    set(0,'DefaultFigureRenderer','painters')

    % Timevector
    timevector = [-9000:9000];

    % Plot timecourses 
    figure
    hold on
    xlabel('Time (ms)')

    % Y-axis parameters

    % Pupil
    if isequal(data_type,'pupil')

        ylabel('Pupil diameter (px)')
        
        % y-limits
        if isequal(event_type,'distractor')
    
            ymin = -115;
            ymax = 450;

        elseif isequal(event_type,'all_stim')

            ymin = -125;
            ymax = 25;

        else

            ymin = -100;
            ymax = 100;

        end

    % Blink
    elseif isequal(data_type,'blink')

        ylabel('Blink fraction (rate)')
        
        % y-limits
        if isequal(event_type,'distractor')
    
            ymin = 0;
            ymax = 0.4;

        elseif isequal(event_type,'all_stim')

            ymin = 0;
            ymax = 0.25;

        else

            ymin = 0;
            ymax = 0.3;
    
        end

    % Microsaccade
    elseif isequal(data_type,'microsaccade')

        ylabel('Microsaccade fraction (rate)')

        % y-limits
        if isequal(event_type,'distractor')
    
            ymin = 0;
            ymax = 0.12;

        elseif isequal(event_type,'all_stim')

            ymin = 0;
            ymax = 0.1;

        else

            ymin = 0;
            ymax = 0.15;
    
        end

    end

    xlim([-1000 6000])
    ylim([ymin ymax])

    % Stimulus times
    plot([0 0],[ymin ymax],'k')
    plot([3000 3000],[ymin ymax],'k')

    % Control data
    if group_type == 0

        title(['Controls - ',data_type,' ',event_type],'Interpreter','none')

        % Plot subject timecourses
        if isequal(data_type,'pupil')

            % Loop over subjects
            for sub = 1:size(group_sighted_matrix,1)

                %plot(timevector,group_left_matrix(sub,:),'b')
                %plot(timevector,group_right_matrix(sub,:),'r')
                plot(timevector,group_sighted_matrix(sub,:),'b')

            end

        end

        % Plot group timecourses
        % plot(timevector,mean_group_left_matrix,'b','LineWidth',5)
        % plot(timevector,mean_group_right_matrix,'r','LineWidth',5)
        % plot(timevector,mean_group_left_matrix+SEM_group_left_matrix,'--b')
        % plot(timevector,mean_group_left_matrix-SEM_group_left_matrix,'--b')
        % plot(timevector,mean_group_right_matrix+SEM_group_right_matrix,'--r')
        % plot(timevector,mean_group_right_matrix-SEM_group_right_matrix,'--r')
        plot(timevector,mean_group_sighted_matrix,'b','LineWidth',5)
        plot(timevector,mean_group_sighted_matrix+SEM_group_sighted_matrix,'--b')
        plot(timevector,mean_group_sighted_matrix-SEM_group_sighted_matrix,'--b')

    % Patient data
    else

        title(['Patients - ',data_type,' ',event_type],'Interpreter','none')

        % Plot timecourses
        plot(timevector,mean_group_blinded_matrix,'k','LineWidth',5)
        plot(timevector,mean_group_sighted_matrix,'g','LineWidth',5)
        plot(timevector,mean_group_blinded_matrix+SEM_group_blinded_matrix,'--k')
        plot(timevector,mean_group_blinded_matrix-SEM_group_blinded_matrix,'--k')
        plot(timevector,mean_group_sighted_matrix+SEM_group_sighted_matrix,'--g')
        plot(timevector,mean_group_sighted_matrix-SEM_group_sighted_matrix,'--g')
    
    end

end